{
 "title": "Utilization Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Used"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Average Disk I/O Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1000 *\r\nsum by (device) (rate(node_disk_read_time_seconds_total[1m]))\r\n/\r\nsum by (device) (rate(node_disk_reads_completed_total[1m]))\r\n",
     "legendFormat": "Disk: {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m]) * 100",
     "legendFormat": "Disk: {{device}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[1m])) by (instance)",
     "legendFormat": "Disk read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[1m])) by (instance)",
     "legendFormat": "Disk write"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"})\r\n  -\r\n  sum(node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"})\r\n)\r\n/\r\nsum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"})\r\n* 100",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"})\n/\nsum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"})\n* 100",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network RX (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "Device: {{device}}"
    }
   ]
  },
  {
   "title": "Network TX (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "Device: {{device}}"
    }
   ]
  }
 ]
}